name: Build Tricycle against standard Cyclus image

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ghcr.io/cyclus/cycamore_24.04_apt/cycamore:latest

    steps:
      - name: Checkout Tricycle
        uses: actions/checkout@v4

      - name: Build Tricycle
        run: |
          install.py 
          
        
