name: Build Tricycle against standard Cyclus image

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/cyclus/cycamore_24.04_apt/cycamore:latest

    steps:
      - name: Checkout Tricycle
        uses: actions/checkout@v4

      - name: Build Tricycle
        run: |
          echo HOME=/root >> "$GITHUB_ENV"
          CYCLUS_ROOT_DIR=/root/.local python3 install.py
          
